export default [
  {
    name: "Model 3",
    tagline: "Order Online for",
    taglineCTA: "Touchless Delivery",
    image: require("../../assets/images/Model3.jpeg"),
    buttonContent: "Custom Order",
    buttonContent2: "Exsisiting Inventory",
    url1: "https://www.tesla.com/model3/design#overview",
    url2: "https://www.tesla.com/inventory/new/ms?arrangeby=relevance&zip=95113&range=200",
  },
  {
    name: "Model Y",
    tagline: "Order Online for",
    taglineCTA: "Touchless Delivery",
    image: require("../../assets/images/ModelY.jpeg"),
    buttonContent: "Custom Order",
    buttonContent2: "Exsisiting Inventory",
    url1: "https://www.tesla.com/modely/design#overview",
    url2: "https://www.tesla.com/inventory/new/my?arrangeby=relevance&zip=95113&range=200",
  },
  {
    name: "Model S",
    tagline: "Order Online for",
    taglineCTA: "Touchless Delivery",
    image: require("../../assets/images/ModelS.jpeg"),
    buttonContent: "Custom Order",
    buttonContent2: "Exsisiting Inventory",
    url1: "https://www.tesla.com/models/design#overview",
    url2: "https://www.tesla.com/inventory/new/my?arrangeby=relevance&zip=95113&range=200",
  },
  {
    name: "Model X",
    tagline: "Order Online for",
    taglineCTA: "Touchless Delivery",
    image: require("../../assets/images/ModelX.jpeg"),
    buttonContent: "Custom Order",
    buttonContent2: "Exsisiting Inventory",
    url1: "https://www.tesla.com/modelx/design#overview",
    url2: "https://www.tesla.com/inventory/new/mx?arrangeby=relevance&zip=95113&range=200",
  },

  {
    name: "Solar Panels",
    tagline: "Lowest Cost Solar Panels in America",
    image: require("../../assets/images/SolarPanels.jpeg"),
    buttonContent: "Order Now",
    buttonContent2: "Learn More",
    url1: "https://www.tesla.com/energy/design",
    url2: "https://www.tesla.com/solarpanels",
  },
  {
    name: "Solar Roof",
    tagline: "Produce Clean Energy From Your Roof",
    image: require("../../assets/images/SolarRoof.jpeg"),
    buttonContent: "Order Now",
    buttonContent2: "Learn More",
    url1: "https://www.tesla.com/energy/design",
    url2: "https://www.tesla.com/solarroof",
  },
];
